zh-lx/code-inspector

- package.json
- packages/core/src/index.ts
- packages/core/src/server/index.ts
- packages/core/src/server/launch-editor.ts
- packages/core/types/index.d.ts
- packages/core/types/server/index.d.ts
- packages/core/types/server/launch-editor.d.ts
- packages/vite-plugin/src/index.ts
- packages/webpack-plugin/src/index.ts
https://github.com/zh-lx/code-inspector/issues/23
> feat: support specifying the editor in config

- docs/README-EN.md
Reverts zh-lx/code-inspector#58
> Revert "feat: 更新英文文档为主文档"

- docs/en/.vitepress/theme/index.ts
- docs/en/guide/api.md
- docs/en/more/changelog.md
- docs/en/more/question.md
- docs/zh/.vitepress/theme/index.ts
- docs/zh/guide/api.md
- docs/zh/more/changelog.md
- docs/zh/more/question.md
- package.json
- packages/code-inspector-plugin/README.md
- packages/code-inspector-plugin/package.json
- packages/core/README.md
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/types/index.d.ts
- packages/vite-plugin/README.md
- packages/vite-plugin/package.json
- packages/vite-plugin/src/index.ts
- packages/vite-plugin/types/index.d.ts
- packages/webpack-plugin/README.md
- packages/webpack-plugin/package.json
- packages/webpack-plugin/src/index.ts
- packages/webpack-plugin/src/loader.ts
- packages/webpack-plugin/types/index.d.ts
- packages/webpack-plugin/types/loader.d.ts
- pnpm-lock.yaml
> Release 0.4.0

- docs/en/more/changelog.md
- docs/zh/more/changelog.md
- package.json
- packages/code-inspector-plugin/package.json
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/server/index.ts
- packages/core/types/index.d.ts
- packages/vite-plugin/package.json
- packages/vite-plugin/src/index.ts
- packages/webpack-plugin/package.json
- packages/webpack-plugin/src/index.ts
- packages/webpack-plugin/src/inject-loader.ts
- packages/webpack-plugin/src/loader.ts
- packages/webpack-plugin/types/index.d.ts
- packages/webpack-plugin/types/inject-loader.d.ts
- packages/webpack-plugin/types/loader.d.ts
- packages/webpack-plugin/vite.inject-loader.config.ts
close #67 
Fix the issue of server not starting and `net::ERR_CONNECTION_REFUSED` error caused by caching.
> Release 0.4.2

- docs/en/guide/api.md
- docs/en/more/changelog.md
- docs/zh/guide/api.md
- docs/zh/more/changelog.md
- packages/code-inspector-plugin/package.json
- packages/core/package.json
- packages/vite-plugin/package.json
- packages/webpack-plugin/package.json
- packages/webpack-plugin/src/index.ts
- packages/webpack-plugin/src/inject-loader.ts
- 【optimize】Enhance the cache strategy for injecting loader in `webpack`, significantly improving the performance of HMR.
> Release 0.5.1

- packages/core/src/client/index.ts
- packages/core/src/server/index.ts
>  fix: 修复+等特殊字符路径文件无法打开的问题

- packages/webpack-plugin/src/index.ts
> fix: node server fails to start with webpack cache

- demos/vite-vue3/vite.config.ts
- packages/core/src/client/index.ts
- packages/core/src/server/use-client.ts
- packages/core/src/shared/type.ts
- packages/core/types/client/index.d.ts
- packages/core/types/shared/type.d.ts
> feat: support custom the behavior

- packages/core/src/server/use-client.ts
> fix: remove vue non-props attributes warning

- packages/core/src/server/launch-editor.ts
- packages/core/src/server/server.ts
- packages/core/src/shared/type.ts
- packages/core/types/server/launch-editor.d.ts
- packages/core/types/server/server.d.ts
- packages/core/types/shared/type.d.ts
> feat: support customize the method of open window

- packages/core/src/server/launch-editor.ts
> fix: custom editor not work in windows

- packages/core/src/server/launch-editor.ts
- 【feat】Optimized IDE prioritization for simultaneously opening multiple IDEs on Windows
- 【fix】Fixed the Issue of failure to automatically recognize IDE path with Chinese Characters on Windows
> feat: optimize IDE Launch Issues on Windows

- packages/core/src/server/use-client.ts
> fix: 优化告警提示

- packages/core/src/server/use-client.ts
> fix: hotKeys not work

- packages/core/src/server/transform/index.ts
- packages/core/src/server/transform/transform-jsx.ts
- packages/core/src/server/transform/transform-svelte.ts
- packages/core/src/server/transform/transform-vue.ts
- packages/core/src/shared/type.ts
- packages/core/src/shared/utils.ts
- packages/core/types/server/transform/index.d.ts
- packages/core/types/server/transform/transform-jsx.d.ts
- packages/core/types/server/transform/transform-svelte.d.ts
- packages/core/types/server/transform/transform-vue.d.ts
- packages/core/types/shared/type.d.ts
- packages/core/types/shared/utils.d.ts
- packages/vite-plugin/src/index.ts
- packages/webpack-plugin/src/index.ts
- packages/webpack-plugin/src/loader.ts
> feat: support customize escapeTags

- packages/core/src/server/use-client.ts
fix: fix the default value of hide dom path attr
> fix: fix the default value of hide dom path attr

- packages/core/src/server/use-client.ts
use a simple way to hide the attribute "data-insp-path".
> pref: hide path attr

- demos/vite-vue3/package.json
- demos/vite-vue3/src/App.vue
- demos/vite-vue3/src/components/pug.vue
- packages/core/package.json
- packages/core/src/server/transform/transform-vue.ts
- pnpm-lock.yaml
> feat: support for pug template in vue

- packages/core/src/client/index.ts
- packages/core/src/server/use-client.ts
- packages/core/src/shared/type.ts
- packages/core/src/shared/utils.ts
- packages/core/types/client/index.d.ts
- packages/core/types/shared/type.d.ts
- packages/core/types/shared/utils.d.ts
> feat: support for sending request by ip

- packages/core/src/server/use-client.ts
- packages/core/src/shared/utils.ts
- packages/core/types/shared/utils.d.ts
> fix: interactive code repeatedly injecting multiple files

- packages/core/src/server/use-client.ts
> fix: interactive code cache causes the configuration to be ineffective

- packages/core/src/server/launch-editor.ts
- packages/core/src/server/transform/transform-jsx.ts
- packages/core/src/shared/type.ts
- packages/core/types/shared/type.d.ts
> opt: optimize the recognition logic of the editor

- packages/core/src/server/use-client.ts
> fix: inject file for nextjs

- packages/core/src/server/use-client.ts
- packages/core/src/shared/type.ts
- packages/core/src/shared/utils.ts
- packages/core/types/shared/type.d.ts
- packages/core/types/shared/utils.d.ts
> feat: optimize client-side code injection logic

- packages/core/src/server/launch-editor.ts
- packages/core/src/shared/type.ts
- packages/core/types/shared/type.d.ts
feat: support cursor
close #206
> feat: support cursor

- packages/core/src/server/use-client.ts
> fix: older browsers not supporting `globalThis`

- packages/core/src/server/use-client.ts
> feat: prevent hydrate warning in nextjs when using hideDomPathAttr

- packages/core/src/server/launch-editor/guess.ts
- packages/core/src/server/launch-editor/index.ts
> fix: compatible for Chinese characters in windows

- packages/core/src/server/use-client.ts
> fix: eliminate warn about hydrate in next v15+

- packages/core/src/client/util.ts
- packages/core/src/vite-env.d.ts
- packages/core/types/client/util.d.ts
> feat: support be used inside web component like wujie

- packages/core/src/server/use-client.ts
- packages/core/src/shared/type.ts
- packages/core/types/shared/type.d.ts
- packages/vite-plugin/src/index.ts
- packages/vite-plugin/types/index.d.ts
- packages/webpack-plugin/src/entry.ts
- packages/webpack-plugin/src/index.ts
- packages/webpack-plugin/types/entry.d.ts
- packages/webpack-plugin/types/index.d.ts
> feat: support mpa project

- packages/core/src/server/use-client.ts
- packages/core/types/server/use-client.d.ts
- packages/esbuild-plugin/src/index.ts
- packages/vite-plugin/src/index.ts
- packages/webpack-plugin/src/index.ts
- packages/webpack-plugin/src/inject-loader.ts
webpack 支持注入代码到 html 文件中，适用部分 MPA 和 SSR 的场景
> feat: inject client code to html

- packages/webpack-plugin/src/index.ts
> fix: webpack assets source is null

- demos/vite-vue3/src/components/HelloWorld.vue
- packages/core/src/client/index.ts
close #90 
fixed no work when click dom whose parentElement is disabled
> fix: no work when click dom whose parentElement is disabled

- packages/core/src/server/launch-editor/guess.ts
improve the performance of guessing editor in windows
> perf: improve the performance of guessing editor in windows

- packages/core/src/client/index.ts
> perf: improve mobile interactive

- packages/core/src/shared/type.ts
- packages/core/src/shared/utils.ts
- packages/core/types/shared/type.d.ts
- packages/core/types/shared/utils.d.ts
- packages/vite-plugin/src/index.ts
- packages/webpack-plugin/src/index.ts
> feat: support monorepo

- packages/core/src/server/use-client.ts
> fix: compatible with instrumentation in nextjs

- packages/core/src/server/server.ts
- packages/core/src/shared/type.ts
- packages/core/types/shared/type.d.ts
> feat: support print server info

- packages/core/src/shared/type.ts
- packages/core/types/shared/type.d.ts
- packages/esbuild-plugin/src/index.ts
- packages/vite-plugin/src/index.ts
- packages/webpack-plugin/src/index.ts
> feat: add exclude option

- packages/core/src/server/use-client.ts
优化 getWebComponentCode 方法，使其更加易读
> feat: optimize getWebComponentCode function

- packages/core/src/client/index.ts
- packages/core/types/client/index.d.ts
> feat: allow to select node and its parent

- package.json
- packages/core/package.json
- pnpm-lock.yaml
upgrade launch-ide to support trae
> deps: upgrade launch-ide to support trae

- packages/core/src/server/server.ts
- packages/core/src/server/transform/index.ts
- packages/core/src/server/transform/transform-jsx.ts
- packages/core/src/server/transform/transform-svelte.ts
- packages/core/src/server/transform/transform-vue.ts
- packages/core/src/shared/type.ts
- packages/core/types/server/server.d.ts
- packages/core/types/server/transform/index.d.ts
- packages/core/types/shared/type.d.ts
- packages/esbuild-plugin/src/index.ts
- packages/vite-plugin/src/index.ts
- packages/webpack-plugin/src/loader.ts
> feat: allow config path type which is between relative or absolute

- packages/webpack-plugin/src/index.ts
> feat: compatible for compilation assets in webpack new version

- demos/webpack5-vue3/package.json
- demos/webpack5-vue3/src/App.vue
- demos/webpack5-vue3/src/components/pug.vue
- demos/webpack5-vue3/vue.config.js
- packages/core/src/server/transform/transform-vue.ts
> fix: compatible for pug syntax in vue with webpack

- packages/core/src/client/index.ts
> fix: client event blocked by custom code sometimes

- packages/core/src/server/use-client.ts
> fix: client component duplicated registration

- demos/vite-vue3/src/components/pug.vue
- packages/core/package.json
- packages/core/src/server/transform/transform-vue.ts
- pnpm-lock.yaml
- support `class` 、`id`、`conditional`、`case`、`code`、`each`、`while`、`when` syntax of pug.
- support pug in HMR
close #296
> fix: support some syntax of pug

- packages/webpack-plugin/src/index.ts
> fix: compatible for rspack with persistent cache

- package.json
- packages/core/package.json
- pnpm-lock.yaml
> feat: support trae CN

- packages/core/src/server/transform/transform-svelte.ts
> fix: support svelte with ts/less/sass .etc

- demos/vite-vue3/src/App.vue
- demos/vite-vue3/src/components/src-temp.html
- demos/vite-vue3/src/components/src-temp.vue
- packages/vite-plugin/src/index.ts
- packages/vite-plugin/types/index.d.ts
> feat: support vue template src

- demos/webpack5-vue3/src/App.vue
- demos/webpack5-vue3/src/components/src-temp.html
- demos/webpack5-vue3/src/components/src-temp.vue
- packages/vite-plugin/src/index.ts
- packages/webpack-plugin/src/index.ts
- packages/webpack-plugin/src/loader.ts
> Feat vue template src

- packages/core/src/server/server.ts
> feat: add validation for the file to open

- packages/webpack-plugin/src/index.ts
- packages/webpack-plugin/src/loader.ts
> feat: exclude and include logic for webpack/rspack

- packages/core/src/server/use-client.ts
> fix: entry starts with use client

- packages/core/src/server/use-client.ts
- packages/core/types/server/use-client.d.ts
- packages/webpack-plugin/src/index.ts
> fix: webpack not support export in inject loader

- packages/core/src/server/server.ts
- packages/core/src/server/use-client.ts
- packages/core/src/shared/type.ts
- packages/core/src/shared/utils.ts
- packages/core/types/shared/type.d.ts
- packages/core/types/shared/utils.d.ts
> fix: perf the record cache

- packages/core/src/server/use-client.ts
> fix: compatible for multiple page of nextjs

- packages/core/src/server/use-client.ts
- packages/core/vite.client.config.ts
> fix: compatible for umijs with app.ts

- packages/core/src/shared/record-cache.ts
> fix(core): findPort maximum call stack #395
